version: "3.9" #version of docker-compose
services:
  mysql:
    container_name: SDBM_DB
    image: orelienthomas/sdbm_db
    ports:
      - "1433:1433"
  web:
    depends_on:
      - mysql
    container_name: SDBM_APP
    image: orelienthomas/sdbm_app
    ports:
      - "8080:8080"